### ISSUE TITLE
Typo in "QueuableJSONDeliveryStream"

### ISSUE THREAD

**Issue by ghost** [mirusresearch/firehoser#9]
Your documentation refers to `new firehoser.QueueableJSONDeliveryStream`, the actual function is named `new firehoser.QueuableJSONDeliveryStream`. You are missing an "e" in the function name.

Thank you!

**Comment by EyePulp** [comment]
Good catch @inciteAnalytics -- Updates made to the classnames and docs where needed.  
Published and in npm now.  This will obviously break for people who upgrade and call the old class names, so we did a minor version bump versus a patch change -- v1.3.5 from v1.2.5 (because I'm a dummy -- meant to do 1.3.0).

Thanks!
